import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * The service worker, served at /sw.js - generated, not a static file, so that EVERY deployment serves different bytes and the browser installs the new worker.
 *
 *   - Its cache is named after the build (`aurelius-static-<build id>`). The previous worker kept one fixed cache name for ever: its precached /offline page (and the
 *     chunks cached next to it) belonged to a deployment that no longer existed, so a page opened with that worker asked for chunks that were gone.
 *   - On activate the new worker deletes every older `aurelius-*` cache, skips waiting and claims the open tabs: a new deploy takes over at once.
 *   - It never answers from a cache while the network works: pages and hashed `/_next/static` files go to the network first; a copy that was cached earlier
 *     (this build only) is used only when the network fails, and a request that fails both ways ends in an ordinary network error - never an uncaught rejection.
 *
 * The build id: the platform's deployment id (Vercel), else the commit, else Next's own `.next/BUILD_ID` (a local `next start`), else "dev".
 */
export const dynamic = "force-dynamic";
export const runtime = "nodejs";

let cachedBuildId: string | null = null;

function currentBuildId(): string {
  if (cachedBuildId) return cachedBuildId;
  let id = process.env.VERCEL_DEPLOYMENT_ID || process.env.VERCEL_GIT_COMMIT_SHA || "";
  if (!id) {
    try {
      id = readFileSync(path.join(process.cwd(), ".next", "BUILD_ID"), "utf8").trim();
    } catch {
      id = "dev";
    }
  }
  cachedBuildId = id.replace(/[^A-Za-z0-9._-]/g, "").slice(0, 80) || "dev";
  return cachedBuildId;
}

function workerSource(buildId: string): string {
  return `// Aurelius IELTS service worker - build ${buildId}. Generated by src/app/sw.js/route.ts; see that file for what it does and why.
const BUILD_ID = ${JSON.stringify(buildId)};
const CACHE_PREFIX = "aurelius-";
const CACHE_NAME = CACHE_PREFIX + "static-" + BUILD_ID;
const OFFLINE_URL = "/offline";
const STATIC_PATTERNS = [/^\\/_next\\/static\\//, /^\\/icons\\//, /^\\/manifest\\.json$/];

function isStaticAsset(url) {
  return url.origin === self.location.origin && STATIC_PATTERNS.some((pattern) => pattern.test(url.pathname));
}

self.addEventListener("install", (event) => {
  // The offline page of THIS deployment, fetched fresh (never from the browser's HTTP cache). A failed precache (offline during the very first install) must not stop the worker.
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.add(new Request(OFFLINE_URL, { cache: "reload" })))
      .catch(() => undefined)
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      try {
        const keys = await caches.keys();
        await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map((key) => caches.delete(key)));
      } catch {
        // Old caches that cannot be deleted now are deleted by the next activation; nothing reads them meanwhile.
      }
      try {
        await self.clients.claim();
      } catch {
        // Not claiming only means the open tabs are taken over at their next navigation.
      }
    })()
  );
});

async function cachedCopy(request) {
  try {
    const cache = await caches.open(CACHE_NAME);
    return (await cache.match(request)) || null;
  } catch {
    return null;
  }
}

// A page load: always the network. Only a failure (no connection) falls back to the offline page - never to a cached copy of a real, per-user page.
async function handleNavigation(request) {
  try {
    return await fetch(request);
  } catch {
    return (await cachedCopy(OFFLINE_URL)) || Response.error();
  }
}

// A hashed or public static file: the network first; what was fetched before (by this build) answers only when the network fails. Whatever happens, this
// function RETURNS a response (a plain network error at worst) - it never rejects.
async function handleStatic(request) {
  try {
    const response = await fetch(request);
    if (response && response.ok && response.type === "basic") {
      try {
        const cache = await caches.open(CACHE_NAME);
        await cache.put(request, response.clone());
      } catch {
        // A full or blocked cache never stops the page from getting its file.
      }
    }
    return response;
  } catch {
    return (await cachedCopy(request)) || Response.error();
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (request.mode === "navigate") {
    event.respondWith(handleNavigation(request));
    return;
  }
  let url;
  try {
    url = new URL(request.url);
  } catch {
    return;
  }
  if (!isStaticAsset(url)) return;
  event.respondWith(handleStatic(request));
});
`;
}

export function GET() {
  return new Response(workerSource(currentBuildId()), {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The browser must look for a new worker on every visit, and no CDN may keep an old one.
      "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
