import "server-only";
import type { ArticleDifficulty, VocabularyStatus } from "@prisma/client";

import { prisma } from "@/lib/prisma";
import { normalizeWord } from "@/lib/vocabulary-word";
import { generateWordIntelligence } from "@/lib/ai/services/word-intelligence";
import { generateWordExplanation } from "@/lib/ai/services/explain-word";
import { AIServiceUnavailableError } from "@/lib/ai/errors";
import { getOpenAIModel } from "@/lib/ai/openai";

export const DEFAULT_DAILY_VOCABULARY_AI_LIMIT = 50;

function startOfToday(): Date {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate());
}

export async function getDailyVocabularyAiLimit(teacherId: string | null): Promise<number> {
  if (!teacherId) return DEFAULT_DAILY_VOCABULARY_AI_LIMIT;
  const settings = await prisma.aiSettings.findUnique({ where: { teacherId } });
  return settings?.dailyVocabularyAiLimit ?? DEFAULT_DAILY_VOCABULARY_AI_LIMIT;
}

/** The combined quota both getWordIntelligence() and explainWord() draw from — "50 AI requests/day", not 50 each. */
async function countTodayFreshRequests(studentId: string): Promise<number> {
  return prisma.vocabularyAiActionLog.count({
    where: { studentId, servedFromCache: false, createdAt: { gte: startOfToday() } },
  });
}

/** Ownership check — a student can only request AI content for a word they've actually saved. Closes the obvious spam/cost-abuse vector of generating content for arbitrary strings. */
async function assertWordIsSaved(studentId: string, word: string) {
  const saved = await prisma.studentVocabulary.findFirst({
    where: { studentId, vocabularyWord: { word } },
    select: { id: true },
  });
  if (!saved) throw new NotSavedError();
}

class NotSavedError extends Error {
  constructor() {
    super("Save this word to your vocabulary first.");
  }
}

export type WordIntelligence = {
  uzbekTranslation: string | null;
  englishDefinition: string | null;
  exampleSentence: string | null;
  synonyms: string[];
  opposites: string[];
  relatedWords: string[];
  wordFamily: { form: string; word: string }[];
  ipaPronunciation: string | null;
  stressPattern: string | null;
  simpleExamples: string[];
  ieltsExamples: string[];
  ieltsDifficulty: ArticleDifficulty | null;
};

export function toWordIntelligence(dict: {
  uzbekTranslation: string | null;
  englishDefinition: string | null;
  exampleSentence: string | null;
  synonyms: unknown;
  opposites: unknown;
  relatedWords: unknown;
  wordFamily: unknown;
  ipaPronunciation: string | null;
  stressPattern: string | null;
  simpleExamples: unknown;
  ieltsExamples: unknown;
  ieltsDifficulty: ArticleDifficulty | null;
}): WordIntelligence {
  return {
    uzbekTranslation: dict.uzbekTranslation,
    englishDefinition: dict.englishDefinition,
    exampleSentence: dict.exampleSentence,
    synonyms: Array.isArray(dict.synonyms) ? (dict.synonyms as string[]) : [],
    opposites: Array.isArray(dict.opposites) ? (dict.opposites as string[]) : [],
    relatedWords: Array.isArray(dict.relatedWords) ? (dict.relatedWords as string[]) : [],
    wordFamily: Array.isArray(dict.wordFamily) ? (dict.wordFamily as { form: string; word: string }[]) : [],
    ipaPronunciation: dict.ipaPronunciation,
    stressPattern: dict.stressPattern,
    simpleExamples: Array.isArray(dict.simpleExamples) ? (dict.simpleExamples as string[]) : [],
    ieltsExamples: Array.isArray(dict.ieltsExamples) ? (dict.ieltsExamples as string[]) : [],
    ieltsDifficulty: dict.ieltsDifficulty,
  };
}

export type GetWordIntelligenceResult =
  | { success: true; data: WordIntelligence; cached: boolean }
  | { success: false; code: "NOT_SAVED" | "RATE_LIMITED" | "UNAVAILABLE"; error: string };

/**
 * The "Word Details AI Panel" (section 1). Cache-first: a word already
 * generated by ANY student is instant for every other student too — the
 * fields live on the shared VocabularyWord row, never regenerated.
 */
export async function getWordIntelligence(
  studentId: string,
  teacherId: string | null,
  rawWord: string
): Promise<GetWordIntelligenceResult> {
  const word = normalizeWord(rawWord);
  if (!word) return { success: false, code: "NOT_SAVED", error: "Not a valid word." };

  try {
    await assertWordIsSaved(studentId, word);
  } catch {
    return { success: false, code: "NOT_SAVED", error: "Save this word to your vocabulary first." };
  }

  const dict = await prisma.vocabularyWord.findUniqueOrThrow({ where: { word } });

  if (dict.aiGeneratedAt) {
    await prisma.vocabularyAiActionLog.create({
      data: { studentId, vocabularyWordId: dict.id, action: "WORD_INTELLIGENCE", servedFromCache: true },
    });
    return { success: true, data: toWordIntelligence(dict), cached: true };
  }

  const limit = await getDailyVocabularyAiLimit(teacherId);
  const usedToday = await countTodayFreshRequests(studentId);
  if (usedToday >= limit) {
    return {
      success: false,
      code: "RATE_LIMITED",
      error: `You've reached today's limit of ${limit} AI vocabulary requests. Try again tomorrow.`,
    };
  }

  let generated;
  try {
    generated = await generateWordIntelligence(word);
  } catch (error) {
    const reason = error instanceof AIServiceUnavailableError ? error.message : "Unknown error.";
    console.error("[ai] word-intelligence generation failed:", reason);
    return { success: false, code: "UNAVAILABLE", error: "AI vocabulary assistant is temporarily unavailable." };
  }

  const updated = await prisma.vocabularyWord.update({
    where: { id: dict.id },
    data: {
      uzbekTranslation: dict.uzbekTranslation ?? generated.uzbekTranslation,
      englishDefinition: dict.englishDefinition ?? generated.englishDefinition,
      exampleSentence: dict.exampleSentence ?? generated.exampleSentence,
      synonyms: generated.synonyms,
      opposites: generated.opposites,
      relatedWords: generated.relatedWords,
      wordFamily: generated.wordFamily,
      ipaPronunciation: generated.ipaPronunciation,
      stressPattern: generated.stressPattern,
      simpleExamples: generated.simpleExamples,
      ieltsExamples: generated.ieltsExamples,
      ieltsDifficulty: generated.ieltsDifficulty,
      aiModel: getOpenAIModel(),
      aiGeneratedAt: new Date(),
    },
  });

  await prisma.vocabularyAiActionLog.create({
    data: { studentId, vocabularyWordId: dict.id, action: "WORD_INTELLIGENCE", servedFromCache: false },
  });

  return { success: true, data: toWordIntelligence(updated), cached: false };
}

export type WordExplanation = {
  meaning: string;
  usage: string;
  commonMistakes: string;
  whenToUse: string;
  whenNotToUse: string;
};

export type ExplainWordResult =
  | { success: true; explanation: WordExplanation; cached: boolean }
  | { success: false; code: "NOT_SAVED" | "RATE_LIMITED" | "UNAVAILABLE"; error: string };

/** The "Explain Word" deep-dive (section 2) — separate cache, separate button, same shared-per-word philosophy. */
export async function explainWord(
  studentId: string,
  teacherId: string | null,
  rawWord: string
): Promise<ExplainWordResult> {
  const word = normalizeWord(rawWord);
  if (!word) return { success: false, code: "NOT_SAVED", error: "Not a valid word." };

  try {
    await assertWordIsSaved(studentId, word);
  } catch {
    return { success: false, code: "NOT_SAVED", error: "Save this word to your vocabulary first." };
  }

  const dict = await prisma.vocabularyWord.findUniqueOrThrow({
    where: { word },
    include: { explanation: true },
  });

  if (dict.explanation) {
    await prisma.vocabularyAiActionLog.create({
      data: { studentId, vocabularyWordId: dict.id, action: "EXPLAIN_WORD", servedFromCache: true },
    });
    return { success: true, explanation: dict.explanation, cached: true };
  }

  const limit = await getDailyVocabularyAiLimit(teacherId);
  const usedToday = await countTodayFreshRequests(studentId);
  if (usedToday >= limit) {
    return {
      success: false,
      code: "RATE_LIMITED",
      error: `You've reached today's limit of ${limit} AI vocabulary requests. Try again tomorrow.`,
    };
  }

  let generated;
  try {
    generated = await generateWordExplanation(word);
  } catch (error) {
    const reason = error instanceof AIServiceUnavailableError ? error.message : "Unknown error.";
    console.error("[ai] explain-word generation failed:", reason);
    return { success: false, code: "UNAVAILABLE", error: "AI vocabulary assistant is temporarily unavailable." };
  }

  // A second identical request (e.g. two students opening the same
  // never-explained word at once) can race this insert against the unique
  // vocabularyWordId constraint — fall back to whichever row won.
  let created;
  try {
    created = await prisma.aiWordExplanation.create({
      data: {
        vocabularyWordId: dict.id,
        meaning: generated.meaning,
        usage: generated.usage,
        commonMistakes: generated.commonMistakes,
        whenToUse: generated.whenToUse,
        whenNotToUse: generated.whenNotToUse,
        model: getOpenAIModel(),
      },
    });
  } catch {
    const existing = await prisma.aiWordExplanation.findUnique({ where: { vocabularyWordId: dict.id } });
    if (!existing) {
      return { success: false, code: "UNAVAILABLE", error: "AI vocabulary assistant is temporarily unavailable." };
    }
    created = existing;
  }

  await prisma.vocabularyAiActionLog.create({
    data: { studentId, vocabularyWordId: dict.id, action: "EXPLAIN_WORD", servedFromCache: false },
  });

  return { success: true, explanation: created, cached: false };
}

// ---------------------------------------------------------------------------
// AI Learning History (section 9)
// ---------------------------------------------------------------------------

export type VocabularyAiHistoryWord = { word: string; at: Date; cached: boolean };

/** Most-recent-first, deduplicated by word — "last viewed" and "recently explained" each mean one row per word, not one per click. */
function dedupeByWord<T extends { vocabularyWord: { word: string } | null; createdAt: Date; servedFromCache: boolean }>(
  rows: T[],
  limit: number
): VocabularyAiHistoryWord[] {
  const seen = new Set<string>();
  const result: VocabularyAiHistoryWord[] = [];
  for (const row of rows) {
    const word = row.vocabularyWord?.word;
    if (!word || seen.has(word)) continue;
    seen.add(word);
    result.push({ word, at: row.createdAt, cached: row.servedFromCache });
    if (result.length >= limit) break;
  }
  return result;
}

export type VocabularyAiActivityRow = {
  id: string;
  word: string | null;
  action: "WORD_INTELLIGENCE" | "EXPLAIN_WORD";
  cached: boolean;
  at: Date;
};

export type VocabularyAiHistory = {
  lastViewed: VocabularyAiHistoryWord[];
  recentlyExplained: VocabularyAiHistoryWord[];
  activity: VocabularyAiActivityRow[];
};

/** Every list here is a real query against VocabularyAiActionLog — no placeholder rows. */
export async function getVocabularyAiHistory(studentId: string, limit = 10): Promise<VocabularyAiHistory> {
  const [viewedRows, explainedRows, activityRows] = await Promise.all([
    prisma.vocabularyAiActionLog.findMany({
      where: { studentId, action: "WORD_INTELLIGENCE" },
      orderBy: { createdAt: "desc" },
      take: limit * 4, // enough raw rows to dedupe down to `limit` distinct words
      include: { vocabularyWord: { select: { word: true } } },
    }),
    prisma.vocabularyAiActionLog.findMany({
      where: { studentId, action: "EXPLAIN_WORD" },
      orderBy: { createdAt: "desc" },
      take: limit * 4,
      include: { vocabularyWord: { select: { word: true } } },
    }),
    prisma.vocabularyAiActionLog.findMany({
      where: { studentId },
      orderBy: { createdAt: "desc" },
      take: 30,
      include: { vocabularyWord: { select: { word: true } } },
    }),
  ]);

  return {
    lastViewed: dedupeByWord(viewedRows, limit),
    recentlyExplained: dedupeByWord(explainedRows, limit),
    activity: activityRows.map((row) => ({
      id: row.id,
      word: row.vocabularyWord?.word ?? null,
      action: row.action,
      cached: row.servedFromCache,
      at: row.createdAt,
    })),
  };
}

// ---------------------------------------------------------------------------
// Dashboard widget: Word of the Day (section 10)
// ---------------------------------------------------------------------------

export type WordOfTheDay = {
  word: string;
  status: VocabularyStatus;
  translation: string | null;
  definition: string | null;
  hasAiInsights: boolean;
};

/**
 * Deterministic per student per calendar day — no OpenAI call here, ever
 * (a dashboard widget must never add AI latency to the page load). Picks
 * from the student's own real saved words only; shows whatever real data
 * already exists, honestly null/absent if this word has never been
 * AI-explored yet, rather than fabricating anything.
 */
export async function getWordOfTheDay(studentId: string): Promise<WordOfTheDay | null> {
  const total = await prisma.studentVocabulary.count({ where: { studentId } });
  if (total === 0) return null;

  const dayIndex = Math.floor(Date.now() / 86_400_000);
  const skip = dayIndex % total;

  const [row] = await prisma.studentVocabulary.findMany({
    where: { studentId },
    orderBy: { addedAt: "asc" },
    skip,
    take: 1,
    include: { vocabularyWord: true },
  });
  if (!row) return null;

  return {
    word: row.vocabularyWord.word,
    status: row.status,
    translation: row.vocabularyWord.uzbekTranslation,
    definition: row.vocabularyWord.englishDefinition,
    hasAiInsights: row.vocabularyWord.aiGeneratedAt != null,
  };
}
